<?xml version="1.0" encoding="utf-8"?><Database Name="login" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-4KB53LB\SQLEXPRESS;Initial Catalog=login;Integrated Security=True" SettingsObjectName="Login.Properties.Settings" SettingsPropertyName="loginConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.info" Member="infos">
    <Type Name="info">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Fname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="passwords" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="usertype" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_login" Method="sp_login">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_loginResult">
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="passwords" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="usertype" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_type" Method="sp_type">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>